name: Build Static Binaries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: mips32-softfloat
            toolchain: mips-unknown-linux-muslsf
            flags: "-march=mips32 -msoft-float"

          - name: mips32-hardfloat
            toolchain: mips-unknown-linux-musl
            flags: "-march=mips32 -mhard-float"

          - name: mips32el-softfloat
            toolchain: mipsel-unknown-linux-muslsf
            flags: "-march=mips32 -msoft-float -EL"

          - name: mips32el-hardfloat
            toolchain: mipsel-unknown-linux-musl
            flags: "-march=mips32 -mhard-float -EL"

          - name: mips64
            toolchain: mips64-unknown-linux-musl
            flags: "-march=mips64"

          - name: mips64el
            toolchain: mips64el-unknown-linux-musl
            flags: "-march=mips64 -EL"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils

      - name: Download and install musl toolchain
        run: |
          TOOLCHAIN_URL="https://github.com/cross-tools/musl-cross/releases/download/20250520/${{ matrix.target.toolchain }}.tar.xz"
          wget --tries=3 $TOOLCHAIN_URL
          tar -xJf ${{ matrix.target.toolchain }}.tar.xz
          echo "$(pwd)/${{ matrix.target.toolchain }}/bin" >> $GITHUB_PATH

      - name: Build binary
        run: |
          CC=${{ matrix.target.toolchain }}-gcc
          $CC -static -O2 -Wall -g0 ${{ matrix.target.flags }} -o wg-obfuscator-${{ matrix.target.name }} wg-obfuscator.c config.c

      - name: Strip binary for minimal size
        run: |
          STRIP=${{ matrix.target.toolchain }}-strip
          $STRIP --strip-all wg-obfuscator-${{ matrix.target.name }}

      - name: Verify binary (optional)
        run: |
          file wg-obfuscator-${{ matrix.target.name }}  # Should now show 'stripped' without debug_info

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: wg-obfuscator-${{ matrix.target.name }}
          path: wg-obfuscator-${{ matrix.target.name }}
